name: Build & Deploy WordPress (ECR + ASG Refresh)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-1
  ECR_REPO: 597765856364.dkr.ecr.eu-west-1.amazonaws.com/custom-wordpress
  ECR_REGISTRY: 597765856364.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_TAG: latest
  ASG_NAME: wp-asg

jobs:
  build_push_refresh:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::597765856364:role/GitHubActionsECRDeployRole

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to ECR
        run: |
          set -euxo pipefail
          aws ecr get-login-password --region "${AWS_REGION}" \
            | docker login --username AWS --password-stdin "${ECR_REGISTRY}"

      - name: Build image
        run: |
          set -euxo pipefail
          docker build -t custom-wordpress:${IMAGE_TAG} .

      - name: Tag & Push image to ECR
        run: |
          set -euxo pipefail
          docker tag custom-wordpress:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
          docker push ${ECR_REPO}:${IMAGE_TAG}

      - name: Start ASG Instance Refresh (skip if already running)
        run: |
          set -euxo pipefail
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "${ASG_NAME}" \
            --preferences MinHealthyPercentage=50,InstanceWarmup=180 \
            --region "${AWS_REGION}" \
          || (echo "Instance refresh already in progress. Skipping."; exit 0)
